apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-api
  labels:
    app: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: registry.digitalocean.com/kimschles/example-api:latest
        ports:
        - containerPort: 4000
